### PR TITLE
Use ActiveRecord.timestamped_migrations

### LINKED ISSUE #349: Rails 7.1 support
### Configuration

- Sorcery Version: `2.0.9`
- Ruby Version: `3.2.2`
- Framework: `Rails`
- Platform: `Mac`

### Expected Behavior

Generator 

Generator should run successfully.

### Actual Behavior

`/Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0.rc1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `timestamped_migrations' for ActiveRecord::Base:Class (NoMethodError)
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:78:in `next_migration_number'
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc1/lib/rails/generators/migration.rb:43:in `set_migration_assigns!'
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc1/lib/rails/generators/migration.rb:59:in `migration_template'
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:65:in `copy_migration_files'
`

### Steps to Reproduce

1. Run `rails generate sorcery:install`

### LINKED ISSUE #353: generate sorcery:install fails because of depricated function "timestamped_migrations"
### Configuration

- Sorcery Version: `0.16.5`
- Ruby Version: `3.2.2`
- Framework: `Rails 7.1.1`
- Platform: `MacOSX Arm64`

### Expected Behavior

'rails generate sorcery:install' should run through without any errors 

### Actual Behavior

The install script stops at creating the user migration. The error is:

´´´
Users/me/.frum/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `timestamped_migrations' for ActiveRecord::Base:Class (NoMethodError)
´´´

Issue is that the function used in the install has been deprecated for quite some time:
https://apidock.com/rails/ActiveRecord/Base/timestamped_migrations/class

My quick fix:

In sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:
´´´
     private
      
      def self.next_migration_number(dirname)
        sleep 1 # make sure each time we get a different timestamp
        Time.now.utc.strftime('%Y%m%d%H%M%S')
      end
´´´

### Steps to Reproduce

Follow install instructions as described here on GitHub
1. install fresh rails 7.1.1 app 
2. add 'gem 'sorcery'' to the Gemfile
3. run 'bundle install'
4. run 'rails g sorcery:install'

### PR DESCRIPTION
**Pull request by Spone**
Replace `ActiveRecord::Base.timestamped_migrations` with the newer `ActiveRecord.timestamped_migrations`

Internally, current versions of Rails use this syntax: https://github.com/search?q=repo%3Arails%2Frails%20timestamped_migrations&type=code

Close #349, close #353

### CODE REVIEW

**Comment by Spone** [comment]
:wave: @joshbuker mind having a quick look?

**Comment by MSILycanthropy** [comment]
Any updates on this?

**Review by joshbuker — APPROVED** [review]
Looks like this accidentally included your other PR code as well, which confused me for a second. Looks good otherwise, and doesn't break our specs.

**Comment by Spone** [comment]
Thanks for checking this out @joshbuker! Any clue why the pipeline is failing? Doesn't seem related to my code 🤨

**Comment by joshbuker** [comment]
Looks like some version conflicts popped up?

There's another PR fixing the test suite, I'll merge that into main and then into the PR and see if it resolves the issue.

**Review by joshbuker — APPROVED** [review]

**Comment by dylhack** [comment]
lol glad to catch you on mastodon. Thanks a ton!

**Comment by joshbuker** [comment]
@dylhack @Spone, this is released as 0.17.0. Let me know if things break horribly; there's a CSRF test that fails in 7.1 that I have no idea what's going on with and has me a bit worried.

**Pull request merged**
