### PR TITLE
Add Magic Login submodule

### PR DESCRIPTION
**Pull request by athix**
Moved from [#766](https://github.com/NoamB/sorcery/pull/766) by @tomomichi.

Still needs documentation and testing, help is welcome.

### CODE REVIEW

**Comment by Ch4s3** [comment]
If @Tomomichi doesn't have time I'll take a look this weekend.

**Comment by Tomomichi** [comment]
@Ch4s3 Sorry for taking this so long and thank you for your offer. That would be a great help.

**Comment by athix** [comment]
@kyuden, @dankimio, this would be a good one to look at if you can.

**Comment by Ch4s3** [comment]
@athix This looks pretty good. Do we want to roll this in under `0.10`? Might make sense.

**Comment by athix** [comment]
@Ch4s3 wouldn't be a bad idea. Needs reviewed and conflicts resolved though.

**Comment by Ch4s3** [comment]
@athix I fixed the conflict, and it looks fine, I'd feel better if it had a test, so we can give ourselves a bit of safety net.

**Comment by athix** [comment]
@Ch4s3 Yeah, wouldn't want to push out a new submodule without decent testing in place first. Honestly, might be better to hold this off for a later release, just so it doesn't cause complications with the Rails 5 release in `0.10.0`. Adding this submodule as part of `0.10.1` or `0.11.0` would work just as fine IMO.

**Comment by Ch4s3** [comment]
I think that's a good call. Perhaps we can roll this in with any `0.10.0` bug fixes and call it `0.11.0`. Then for `1.0` I want to start pulling the submodules out into independent gems.

**Comment by Ch4s3** [comment]
@Tomomichi We haven't forgotten your PR. If you add some tests, we'll release it in the near future!

**Comment by Ch4s3** [comment]
Let's slate this for 0.11.0 and do some work on it soon.

**Comment by Ch4s3** [comment]
@athix let's try to get this one moving again. I'll try to take a look asap.

**Comment by ebihara99999** [comment]
I started working on adding tests, but it seems to take long to complete.

**Comment by ebihara99999** [comment]
@athix 
I've added specs of magic login submodules and would like to review them. But I don't know how to open a PR from others' working on and not completed. 
If it's OK to open a PR as a new, I will do; If it's not, would you tell me the best way?
This is [the branch](https://github.com/ebihara99999/sorcery/tree/feature/magic-login) working on.

**Comment by Ch4s3** [comment]
@ebihara99999 are you asking if you can open a new PR with your work? If so, then yes of course you may! Please do in fact! Sorry for the delay.

**Comment by ebihara99999** [comment]
@Ch4s3 
Thanks! I opened a PR just now. Would you review it? 
And thank you for dealing with many issues and PRs. I really appreciate it.

**Comment by Ch4s3** [comment]
closing as #95 addresses this PR

**Pull request closed without merging**
