### PR TITLE
Fix deprecation warnings in Rails 6

### PR DESCRIPTION
**Pull request by tobyaherbert**
Sorcery currently uses ```defined?``` checks in ```engine.rb``` which causes Rails to autoload those constants during initialization. This generates deprecation warnings when using Rails 6:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /path/to/rails-6-app/config/environment.rb:5)
```

Using the ```#on_load``` method provided ActiveSupport fixes this problem.

---

I found these similar GitHub Issues whilst researching this:
- https://github.com/rollbar/rollbar-gem/issues/880
- https://github.com/rails/rails/issues/36546

### CODE REVIEW

**Comment by athix** [comment]
I'm pretty sure when I tried to change it to `on_load` here before, we ran into some hefty gotchas that broke applications. I'll see if I can use `git blame` to find what the reason was.

**Comment by tobyaherbert** [comment]
@athix Perfect, thanks for looking into this :)

**Comment by athix** [comment]
@tobyaherbert Sorry for taking so long! Tried this locally and it `worked on my machine™`. Merged in the TravisCI fixes, and will hopefully have this merged and deployed to a new gem release shortly.

**Comment by tobyaherbert** [comment]
@athix No problem! Thanks for looking into this 👍

**Comment by Hirurg103** [comment]
Hello Guys,
I encountered the same issue. How can I use the new version of sorcery that includes this fix 

Change sorcery line in the Gemfile to `gem 'sorcery', github: 'Sorcery/sorcery', branch: 'master'`?

Or maybe it will be better to add prerelease version (for example `0.14.0.1`) that will include this fix until the next stable version of sorcery will be released?

**Comment by Hirurg103** [comment]
Hello Guys,
I encountered the same issue. How can I use the new version of sorcery that includes this fix? 

Change sorcery line in the Gemfile to `gem 'sorcery', github: 'Sorcery/sorcery', branch: 'master'`?

Or maybe it will be better to add prerelease version (for example `0.14.0.1`) that will include this fix until the next stable version of sorcery will be released?

**Comment by Hirurg103** [comment]
Thank you for this fix @tobyaherbert 

I encountered the same issue. @athix , I want to change my app to use the new code of Sorcery that includes this fix. Is it safe to use `master` branch of this repo with
```ruby
# Gemfile
gem 'sorcery', github: 'Sorcery/sorcery', branch: 'master'`
```

What do you think of adding prerelease version (for example 0.14.0.1) that will include this fix until the next stable version of Sorcery will be released?

When are you planning to release the new version of Sorcery?

**Comment by Hirurg103** [comment]
Thank you for this fix @tobyaherbert 

I encountered the same issue. @athix , I want to change my app to use the new code of Sorcery that includes this fix. Is it safe to use `master` branch of this repo with
```ruby
# Gemfile
gem 'sorcery', github: 'Sorcery/sorcery', branch: 'master'
```

What do you think of adding prerelease version (for example 0.14.0.1) that will include this fix until the next stable version of Sorcery will be released?

When are you planning to release the new version of Sorcery?

**Comment by athix** [comment]
@Hirurg103 using master should be (relatively) safe, just ensure that you're using https, and be diligent to keep an eye on if the git hash changes.

I was hoping to get @mladenilic familiar with the deployment process, but if it's important to get a version out sooner rather than later, I can focus on getting that done in the next few days.

@mladenilic let me know if you're available (and still interested) in doing this.

**Comment by Hirurg103** [comment]
Hi @athix thank you for paying attention to this 🙇

**Comment by athix** [comment]
Putting the next release on hold until master is confirmed working, see #227.

**Comment by wout** [comment]
FWIW, I've been testing this in a Rails 6.0.3.2 app with Ruby 2.7.1. All specs pass and I can't see any other issues.

**Pull request merged**
