### PR TITLE
Refactor by using rubocop

### PR DESCRIPTION
**Pull request by asmsuechan**
Before
```
113 files inspected, 2864 offenses detected
```

After
```
113 files inspected, 2768 offenses detected
```

We should discuss about .rubocop.yml.

### CODE REVIEW

**Comment by asmsuechan** [comment]
@athix  A bug is fixed in 576d437 detected by 9e04c7c. Until then, spec passed because of exec order of 'or'.

**Comment by athix** [comment]
Thanks for getting this started! Might take a while with 2000+ offenses, so if anyone else wants to help out on this, I'd appreciate it.

@asmsuechan, good catch with that bug. If you could actually pull that change out into a separate PR, then we can merge it right away and use this PR for working on the rubocop offenses.

**Comment by asmsuechan** [comment]
Thanks for your review @athix!
I opened a [PR](https://github.com/Sorcery/sorcery/pull/22) about the bug. Please check it.
I'll remove the commit.

Probably we'll have troublesome conflicts problem on this PR...

**Comment by asmsuechan** [comment]
Or, should I open separate PRs in piaces?

**Comment by dankimio** [comment]
@asmsuechan Can you rebase your branch from master?

**Comment by asmsuechan** [comment]
@dankimio sorry for my absent. I try to continue. Thank you!

**Pull request merged**
