### PR TITLE
Support line login v2.1

### PR DESCRIPTION
**Pull request by kentarohorie**
Support for LINE login v2.1. ref: https://github.com/Sorcery/sorcery/pull/80  
doc -> https://developers.line.biz/en/docs/line-login/integrate-line-login/#login-flow

I proposed because I need bot_prompt function. It's enable you to add [LINE Bot](https://developers.line.biz/en/docs/messaging-api/overview/) when login with line.

### What is LINE?
https://github.com/Sorcery/sorcery/pull/80#issuecomment-327351210

> LINE is the most popular messaging application in Japan. But, it is not popular outside Japan.
LINE is similar to WhatsApp or Facebook Messenger.
About 70% of Japanese are using it, and it is used for 500 million people all over the world.

https://en.wikipedia.org/wiki/Line_(software)

### CODE REVIEW

**Comment by ShunFurukawa** [comment]
👍 

@kentarohorie thx :D 
I was also asking for this! 
hope it will be merged 👍

**Comment by athix** [comment]
Just need to solve CI being wonky. I'm pretty slammed this week, but I'll come back to this when I have time available.

**Comment by athix** [comment]
Webhooks are enabled and seem to be firing on events, it's weird that CI worked for a period and only just now broke again. Guessing TravisCI changed something about how the webhooks are configured? Either that or it changed on the Github side.

Unfortunately no solution yet, but I'll investigate some more later.

**Comment by athix** [comment]
Seems that TravisCI is reading new PRs just fine, so it's most likely on the Github side of things.

The build is passing, so I'll go ahead and merge this in manually. I can work on fixing TravisCI separately.

**Comment by kentarohorie** [comment]
Thanks! I'm happy to contribute to sorcery

**Pull request merged**
